all:
	clear
	gcc OSLab_2.c -Wall -Wextra -Werror -pedantic-errors -Wformat=2 -Winit-self -Wstrict-overflow=5 -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Waggregate-return -o Lab_2 
	./Lab_2