all:
	clear
	gcc OSLab_1.c -Wall -Wextra -Werror -pedantic-errors -Wformat=2 -Winit-self -Wstrict-overflow=5 -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Waggregate-return -o Lab_1 
	./Lab_1